project:
  type: website
  output-dir: docs/

website:
  title: "InforBio"
  site-url: https://inforbio.github.io/
  favicon: images/logoInforBio_fond_blanc.png
  
  page-footer: 
    right: "This page is built with [Quarto](https://quarto.org/)"
    # left: "&copy; CC-By InforBio"
    
  navbar:
    logo: images/logoInforBio_fond_blanc.png
    left:
      - href: index.qmd
        text: "About US"
      - text: "Trainings"
        menu: 
          - text: "What is IOC?"
            href: what_is_ioc.qmd
          - text: "IOC R & scRNAseq"
            href: ioc_r_scrnaseq.qmd
          - text: "IOC Bulk RNAseq"
            href: ioc_bulk_rnaseq.qmd
      # - text: "News"
      #   href: news.qmd
      - icon: github
        href: https://github.com/InforBio/InforBio.github.io


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



